# Generated by Django 4.2 on 2023-05-10 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eden", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="body",
        ),
    ]
